credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$O9TfjaY0S0FaRRPPCMNmWepakcQvjB10qRNPr/ErhAv2Y9BeKSvpW
    nkdhapekar:
      email: nishikant.dhapekar@kalingauniversity.ac.in
      name: N K Dhapekar
      password: $2b$12$0XldfcfDA7TZGwTM3MHdJeoCS9JW88qoAt4mhAunC3M9oy4eAeeQu
    sharmas:
      email: sharma@besoins.in
      name: Sharma Saravanan
      password: $2b$12$O9TfjaY0S0FaRRPPCMNmWepakcQvjB10qRNPr/ErhAv2Y9BeKSvpW
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com